{% set name = "specialist" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/specialist-{{ version }}.tar.gz
  sha256: 9b69870703f09412df6c4c154bb8d0b7681b6d0e8d529c142a898ef7aac94145

build:
  entry_points:
    - specialist=specialist:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - specialist
  commands:
    - pip check
    - specialist --help
  requires:
    - pip

about:
  home: https://github.com/brandtbucher/specialist
  summary: Visualize CPython 3.11's specializing, adaptive interpreter.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
